{% set name = "pyrootutils" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyrootutils-{{ version }}.tar.gz
  sha256: f58aac67147bbab20938b7b783cb2f4670d6329a33c6640233854976538fc5f2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - python-dotenv >=0.20.0

test:
  imports:
    - pyrootutils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ashleve/pyrootutils
  summary: Simple package for easy project root setup
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
